// Ratio tree definitions. Each node reads its value from computeRatios().
// Leaves carry a what-if slider that changes one driver in the sample company.

const pct = (v) => `${(v * 100).toFixed(1)}%`;
const times = (v) => `${v.toFixed(2)}x`;
const days = (v) => `${v.toFixed(0)} d`;

export const FORMATS = { pct, times, days };

export const DUPONT = {
  id: 'roe',
  label: 'ROE',
  value: (r) => r.roe,
  fmt: pct,
  higherIsBetter: true,
  topic: 'dupont',
  formula: 'Net income ÷ Equity = Net margin × Asset turnover × Equity multiplier',
  meaning: 'Return on the shareholders’ money. DuPont splits it into profitability, efficiency and leverage so you can see which lever is doing the work.',
  chain: ['Net margin ↑ → ROE ↑ (better operations)', 'Asset turnover ↑ → ROE ↑ (sweating assets)', 'Equity multiplier ↑ → ROE ↑ but risk ↑ (financial engineering)'],
  children: [
    {
      id: 'nm',
      label: 'Net margin',
      value: (r) => r.netMargin,
      fmt: pct,
      higherIsBetter: true,
      topic: 'profitability',
      formula: 'Net income ÷ Revenue = EBIT margin × Tax & interest burden',
      meaning: 'How much of each unit of revenue reaches shareholders after all costs, interest and tax.',
      chain: ['Gross margin ↓ → EBIT margin ↓ → net margin ↓ → ROE ↓', 'Interest ↑ → interest burden ↓ → net margin ↓'],
      children: [
        {
          id: 'gm',
          label: 'Gross margin',
          value: (r) => r.grossMargin,
          fmt: pct,
          higherIsBetter: true,
          topic: 'profitability',
          formula: '(Revenue − COGS) ÷ Revenue',
          meaning: 'Pricing power and direct cost efficiency. The first line a competitor or input-cost shock hits.',
          chain: ['Gross margin ↓ → EBIT ↓ → net margin ↓ → ROE ↓', 'COGS ↑ → inventory and payables (in days) re-scale with it'],
          slider: { key: 'gm', label: 'Gross margin change', min: -5, max: 5, step: 0.5, unit: 'pts' },
        },
        {
          id: 'opex',
          label: 'Opex / sales',
          value: (r) => r.opexToSales,
          fmt: pct,
          higherIsBetter: false,
          topic: 'profitability',
          formula: '(Operating costs + D&A) ÷ Revenue',
          meaning: 'Overhead intensity. Falls with scale when costs are fixed (operating leverage), rises when you invest ahead of growth.',
          chain: ['Opex/sales ↑ → EBIT margin ↓ → net margin ↓ → ROE ↓', 'Opex/sales ↑ → EBITDA ↓ → net debt/EBITDA ↑'],
          slider: { key: 'opex', label: 'Opex / sales change', min: -5, max: 5, step: 0.5, unit: 'pts' },
        },
        {
          id: 'tib',
          label: 'Tax & interest',
          value: (r) => r.taxInterestBurden,
          fmt: (v) => `× ${v.toFixed(2)}`,
          higherIsBetter: true,
          topic: 'dupont',
          formula: '(EBT ÷ EBIT) × (Net income ÷ EBT) = Net income ÷ EBIT',
          meaning: 'The share of operating profit left after lenders and the tax authority. Closer to 1 means less leakage.',
          chain: ['Tax rate ↑ → tax burden ↓ → net margin ↓ → ROE ↓', 'More debt → interest ↑ → interest burden ↓ (but equity multiplier ↑)'],
          slider: { key: 'taxRate', label: 'Tax rate change', min: -10, max: 10, step: 1, unit: 'pts' },
        },
      ],
    },
    {
      id: 'at',
      label: 'Asset turnover',
      value: (r) => r.assetTurnover,
      fmt: times,
      higherIsBetter: true,
      topic: 'efficiency',
      formula: 'Revenue ÷ Total assets',
      meaning: 'How much revenue each unit of assets generates. Capital-light models run high turnover; heavy industry runs low.',
      chain: ['Receivables or inventory ↑ → assets ↑ → asset turnover ↓ → ROE ↓', 'Assets ↑ → more funding needed → debt ↑'],
      children: [
        {
          id: 'dso',
          label: 'DSO',
          value: (r) => r.dso,
          fmt: days,
          higherIsBetter: false,
          topic: 'efficiency',
          formula: 'Receivables ÷ Revenue × 365',
          meaning: 'Days it takes to collect cash from customers. Rising DSO means you are financing your customers.',
          chain: ['DSO ↑ → receivables ↑ → asset turnover ↓ → ROE ↓', 'DSO ↑ → working capital ↑ → CFO ↓ → debt need ↑'],
          slider: { key: 'dso', label: 'DSO change', min: -30, max: 30, step: 1, unit: 'days' },
        },
        {
          id: 'dio',
          label: 'DIO',
          value: (r) => r.dio,
          fmt: days,
          higherIsBetter: false,
          topic: 'efficiency',
          formula: 'Inventory ÷ COGS × 365',
          meaning: 'Days of stock on hand. Rising DIO can mean slowing demand, obsolete stock or deliberate safety stock.',
          chain: ['DIO ↑ → inventory ↑ → asset turnover ↓ → ROE ↓', 'DIO ↑ → cash conversion cycle ↑ → CFO ↓'],
          slider: { key: 'dio', label: 'DIO change', min: -30, max: 30, step: 1, unit: 'days' },
        },
        {
          id: 'fat',
          label: 'Fixed asset turn',
          value: (r) => r.fixedAssetTurnover,
          fmt: times,
          higherIsBetter: true,
          topic: 'efficiency',
          formula: 'Revenue ÷ Net PP&E',
          meaning: 'Revenue per unit of fixed assets. Falls when capex runs ahead of revenue, rises as plants fill up.',
          chain: ['Capex ahead of demand → PP&E ↑ → fixed asset turn ↓ → asset turnover ↓ → ROE ↓', 'Ageing assets → net PP&E ↓ → turnover ↑ (flatters the ratio)'],
          slider: { key: 'fat', label: 'Fixed asset turnover change', min: -1, max: 1, step: 0.1, unit: 'x' },
        },
      ],
    },
    {
      id: 'em',
      label: 'Equity multiplier',
      value: (r) => r.equityMultiplier,
      fmt: times,
      higherIsBetter: null,
      topic: 'financial_leverage',
      formula: 'Total assets ÷ Equity = 1 + Liabilities ÷ Equity',
      meaning: 'Financial leverage. It lifts ROE without improving the business, and adds risk.',
      chain: ['Debt-funded buyback → equity ↓ → multiplier ↑ → ROE ↑ (risk ↑)', 'More debt → interest ↑ → net margin ↓ (partly offsets)'],
      children: [
        {
          id: 'de',
          label: 'Debt / equity',
          value: (r) => r.debtToEquity,
          fmt: times,
          higherIsBetter: null,
          topic: 'solvency',
          formula: '(Debt + Lease liabilities) ÷ Equity',
          meaning: 'How much lenders fund for each unit of equity. Use the slider to raise equity and repay debt (deleverage).',
          chain: ['Equity raise → debt ↓ → D/E ↓ → multiplier ↓ → ROE ↓ (but safer)', 'Debt ↓ → interest ↓ → net margin ↑ (partly offsets)'],
          slider: { key: 'equityRaise', label: 'Equity raised to repay debt', min: 0, max: 200, step: 10, unit: 'cur' },
        },
        {
          id: 'buyback',
          label: 'Buybacks',
          value: (r) => r.buyback,
          fmt: (v) => (v ? `${v.toFixed(0)}` : 'none'),
          higherIsBetter: null,
          topic: 'buybacks',
          formula: 'Cash or new debt used to repurchase shares → equity ↓',
          meaning: 'A buyback shrinks equity. Funded with debt, it raises both the equity multiplier and interest cost.',
          chain: ['Buyback ↑ → equity ↓ → multiplier ↑ → ROE ↑', 'Buyback funded with debt → interest ↑ → net margin ↓ → interest cover ↓'],
          slider: { key: 'buyback', label: 'Debt-funded buyback', min: 0, max: 200, step: 10, unit: 'cur' },
        },
        {
          id: 'leases',
          label: 'Leases',
          value: (r) => r.leaseLiabilities,
          fmt: (v) => `${v.toFixed(0)}`,
          higherIsBetter: null,
          topic: 'leases',
          formula: 'IFRS 16: right-of-use asset = lease liability on the balance sheet',
          meaning: 'Leases sit on the balance sheet as debt-like liabilities. New leases grow assets and liabilities together.',
          chain: ['New leases → assets ↑ and liabilities ↑ → asset turnover ↓, multiplier ↑', 'Lease interest ↑ → interest burden ↓ → net margin ↓'],
          slider: { key: 'newLeases', label: 'New lease liabilities', min: 0, max: 200, step: 10, unit: 'cur' },
        },
      ],
    },
  ],
};

export const ROIC_TREE = {
  id: 'roic',
  label: 'ROIC',
  value: (r) => r.roic,
  fmt: pct,
  higherIsBetter: true,
  topic: 'roic_tree',
  formula: 'NOPAT ÷ Invested capital = NOPAT margin × Invested-capital turnover',
  meaning: 'Return on all the capital in the business, before financing choices. Compare it with WACC: value is created only when ROIC > WACC.',
  chain: ['NOPAT margin ↑ → ROIC ↑', 'Invested capital ↓ for the same revenue → IC turnover ↑ → ROIC ↑', 'ROIC is unaffected by buybacks or debt mix'],
  children: [
    {
      id: 'nopm',
      label: 'NOPAT margin',
      value: (r) => r.nopatMargin,
      fmt: pct,
      higherIsBetter: true,
      topic: 'roic_tree',
      formula: 'EBIT × (1 − cash tax rate) ÷ Revenue',
      meaning: 'Operating profit after tax per unit of revenue, independent of how the company is financed.',
      chain: ['Gross margin ↓ → EBIT ↓ → NOPAT margin ↓ → ROIC ↓', 'Cash tax rate ↑ → NOPAT ↓ → ROIC ↓'],
      children: [
        {
          id: 'r_gm',
          label: 'Gross margin',
          value: (r) => r.grossMargin,
          fmt: pct,
          higherIsBetter: true,
          topic: 'profitability',
          formula: '(Revenue − COGS) ÷ Revenue',
          meaning: 'Pricing power and direct cost efficiency.',
          chain: ['Gross margin ↓ → EBIT ↓ → NOPAT margin ↓ → ROIC ↓'],
          slider: { key: 'gm', label: 'Gross margin change', min: -5, max: 5, step: 0.5, unit: 'pts' },
        },
        {
          id: 'r_opex',
          label: 'Opex / sales',
          value: (r) => r.opexToSales,
          fmt: pct,
          higherIsBetter: false,
          topic: 'profitability',
          formula: '(Operating costs + D&A) ÷ Revenue',
          meaning: 'Overhead intensity, including depreciation.',
          chain: ['Opex/sales ↑ → EBIT margin ↓ → NOPAT margin ↓ → ROIC ↓'],
          slider: { key: 'opex', label: 'Opex / sales change', min: -5, max: 5, step: 0.5, unit: 'pts' },
        },
        {
          id: 'r_tax',
          label: 'Cash tax rate',
          value: (r) => r.cashTaxRate,
          fmt: pct,
          higherIsBetter: false,
          topic: 'roic_tree',
          formula: 'Cash taxes paid on operating profit ÷ EBIT (here: the statutory rate)',
          meaning: 'The tax leakage on operating profit. Tax planning and loss carry-forwards change it.',
          chain: ['Cash tax rate ↑ → NOPAT ↓ → ROIC ↓'],
          slider: { key: 'taxRate', label: 'Tax rate change', min: -10, max: 10, step: 1, unit: 'pts' },
        },
      ],
    },
    {
      id: 'ict',
      label: 'IC turnover',
      value: (r) => r.icTurnover,
      fmt: times,
      higherIsBetter: true,
      topic: 'roic_tree',
      formula: 'Revenue ÷ (Net working capital + Net PP&E + Right-of-use assets)',
      meaning: 'Revenue per unit of operating capital. Working-capital discipline and asset intensity drive it.',
      chain: ['Working capital days ↑ → invested capital ↑ → IC turnover ↓ → ROIC ↓', 'Capex ↑ ahead of revenue → IC turnover ↓'],
      children: [
        {
          id: 'r_dso',
          label: 'DSO',
          value: (r) => r.dso,
          fmt: days,
          higherIsBetter: false,
          topic: 'working_capital',
          formula: 'Receivables ÷ Revenue × 365',
          meaning: 'Days to collect from customers.',
          chain: ['DSO ↑ → NWC ↑ → invested capital ↑ → ROIC ↓', 'DSO ↑ → CFO ↓ → debt need ↑'],
          slider: { key: 'dso', label: 'DSO change', min: -30, max: 30, step: 1, unit: 'days' },
        },
        {
          id: 'r_dio',
          label: 'DIO',
          value: (r) => r.dio,
          fmt: days,
          higherIsBetter: false,
          topic: 'working_capital',
          formula: 'Inventory ÷ COGS × 365',
          meaning: 'Days of stock on hand.',
          chain: ['DIO ↑ → NWC ↑ → invested capital ↑ → ROIC ↓'],
          slider: { key: 'dio', label: 'DIO change', min: -30, max: 30, step: 1, unit: 'days' },
        },
        {
          id: 'r_dpo',
          label: 'DPO',
          value: (r) => r.dpo,
          fmt: days,
          higherIsBetter: true,
          topic: 'working_capital',
          formula: 'Payables ÷ COGS × 365',
          meaning: 'Days you take to pay suppliers. Higher DPO means suppliers fund more of your working capital (within reason).',
          chain: ['DPO ↑ → payables ↑ → NWC ↓ → invested capital ↓ → ROIC ↑', 'Stretching suppliers too far → supply risk, worse prices'],
          slider: { key: 'dpo', label: 'DPO change', min: -30, max: 30, step: 1, unit: 'days' },
        },
        {
          id: 'r_fai',
          label: 'Fixed asset intensity',
          value: (r) => r.fixedAssetIntensity,
          fmt: pct,
          higherIsBetter: false,
          topic: 'capex',
          formula: 'Net PP&E ÷ Revenue',
          meaning: 'How much fixed capital the business needs per unit of revenue.',
          chain: ['Capex ahead of revenue → PP&E/sales ↑ → invested capital ↑ → ROIC ↓'],
          slider: { key: 'fai', label: 'PP&E / sales change', min: -10, max: 10, step: 1, unit: 'pts' },
        },
      ],
    },
  ],
};

export const TREES = { dupont: DUPONT, roic: ROIC_TREE };

export function findPath(root, id, path = []) {
  const next = [...path, root];
  if (root.id === id) return next;
  for (const ch of root.children || []) {
    const p = findPath(ch, id, next);
    if (p) return p;
  }
  return null;
}
